name: Build, Test and Release

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true

      - name: Checkout
        uses: actions/checkout@v1

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test -race -covermode=atomic -coverprofile="c.out" -v ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./c.out
          fail_ci_if_error: true
  build:
    needs: [test]
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64, arm64]
    runs-on: ubuntu-latest
    env:
      GO111MODULE: 'on'
      TARGET_GOOS: ${{ matrix.os }}
      TARGET_GOARCH: ${{ matrix.arch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Build
        run: ./scripts/build.sh

      - name: Create Release Draft
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          draft: true
          generate_release_notes: true
          files: grab-*

  purge:
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Purge
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          curl -s https://github.com/${{ github.event.repository.owner.login }}/${{ github.event.repository.name }}/blob/main/README.md > readme.md.tmp
          grep -Eo '<img src="[^"]+"' readme.md.tmp | grep camo | grep -Eo 'https[^"]+' | xargs -I {} curl -w "\n" -s -X PURGE {}
