name: Build, Test and Release

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags: ["v*.*.*"]

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test -race -covermode=atomic -coverprofile="c.out" -v ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./c.out
          fail_ci_if_error: true
  build:
    needs: [test]
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64, arm64]
    runs-on: ubuntu-latest
    env:
      GO111MODULE: "on"
      TARGET_GOOS: ${{ matrix.os }}
      TARGET_GOARCH: ${{ matrix.arch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Build
        run: ${{ matrix.script }}

      - name: Create Release Draft
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          draft: true
          files: grab-*
