name: Test

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.19]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test -race -covermode=atomic -coverprofile="c.out" -v ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./c.out
          fail_ci_if_error: true
